# Generated by Django 5.1 on 2024-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTb',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=100)),
                ('code_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'code_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceTb',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('review_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_tb',
                'managed': False,
            },
        ),
    ]
